project:
  type: website

website:
  favicon: images/RStudio.png

  navbar:
    logo: images/RStudio.png

    left:
      - text: Home
        href: index.qmd

      - text: Tutorials
        menu:
          - text: Transforming Variables
            href: transformingVariables.html

          - text: Making Comparisons
            href: makingComparisons.qmd

          - text: t-tests and ANOVAs
            href: t-tests_ANOVAs.qmd

          - text: Chi-Square
            href: chi-square_measuresOfAssociation.html

          - text: "Subsetting Data: Variable Types"
            href: subsettingVariableTypes.qmd

          - text: Correlations
            href: correlation.qmd

          - text: "OLS: Linear Regressions"
            href: linearRegression1.qmd

          - text: "Logit: Logistic Regressions"
            href: logit_logisticRegression.qmd

          - text: Multivariate Regressions
            href: multivariateRegression.qmd

          - text: Ordinal and Multinomial Logit
            href: ologit_mlogit.html

          - text: Publication-Ready Tables
            href: prettyData.qmd

      - text: Datasets
        menu:
          - text: Spain Replication data
            href: Datasets/spain.RData

          - text: Test Scores data
            href: Datasets/testScoresData.RData

      - text: Scripts
        menu:
          - text: Capstone Script
            href: scripts/CapstoneScriptTemplate.R

      - text: Choosing the Appropriate Tests
        href: choosingTheAppropriateTests.qmd


format:
  html:
    theme: cosmo
    css: styles.css