project:
  type: website

website:
  title: "R Walkthroughs"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - TransformingVariables.qmd
      - chi-square_measuresOfAssociation.qmd
      - ologit_mlogit.qmd

format:
  html:
    toc: true