project:
  type: website
  resources:
    - slides/**
    - scripts/**
    - datasets/**
    - images/**

website:
  favicon: images/RStudio.png

  navbar:
    logo: images/RStudio.png

    left:
      - text: Home
        href: index.qmd

      - text: Tutorials
        menu:
          - text: Transforming Variables
            href: transformingVariables.html

          - text: Making Comparisons
            href: makingComparisons.qmd

          - text: t-tests and ANOVAs
            href: t-tests_ANOVAs.qmd

          - text: Chi-Square
            href: chi-square_measuresOfAssociation.html

          - text: "Subsetting Data: Variable Types"
            href: subsettingVariableTypes.qmd

          - text: Correlations
            href: correlation.qmd

          - text: "OLS: Linear Regressions"
            href: linearRegression1.qmd

          - text: "Logit: Logistic Regressions"
            href: logit_logisticRegression.qmd

          - text: Multivariate Regressions
            href: multivariateRegression.qmd

          - text: Ordinal and Multinomial Logit
            href: ologit_mlogit.html

          - text: Publication-Ready Tables
            href: prettyData.qmd

      - text: Datasets
        menu:
          - text: Spain Replication R data
            href: datasets/spain.RData

          - text: Test Scores R data
            href: datasets/testScoresData.RData

          - text: Pollock R data descriptions
            href: https://docs.google.com/spreadsheets/d/13VKbgVXqIpFhkHK0VcgBzB-0o_CLGFugntq34WwaWp4/edit?usp=sharing
            target: _blank

          - text: Some IR/Comparative datasets
            href: https://docs.google.com/spreadsheets/d/1-ftZTPojKyaPGTIlqkV1Q1a8TvJXqtqQ81YA0k4AtiA/edit?usp=sharing
            target: _blank


      - text: Scripts
        menu:
          - text: Capstone Script
            href: scripts/CapstoneScriptTemplate.R

      - text: Choosing the Appropriate Tests
        href: choosingTheAppropriateTests.qmd


format:
  html:
    theme: cosmo
    css: styles.css